// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DronecounterController from "./dronecounter_controller.js"
application.register("dronecounter", DronecounterController)

import DronetallyController from "./dronetally_controller.js"
application.register("dronetally", DronetallyController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
